services:
  - type: web
    name: sakala-web
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:s9r1K6F8kH7f0vQ4aZ9P1eX7mB3yN5kO6L4uP8iQ2wM=
      - key: APP_URL
        value: https://sakala-web.onrender.com
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: LOG_CHANNEL
        value: stderr
